#!/usr/bin/env bash

# Requirement : le script doit avoir un nom unique sur le système pour que la commande "source" le trouve
if [ -d "./bin" ]; then
  echo "Error: The current directory is not empty. Please remove all contents within this directory and try again."
  exit 1
fi

git init -qqq
git remote add origin https://github.com/ludilabel/docker-magento
git fetch origin -qqq
git checkout release/next
