#!/usr/bin/env bash

# Pour faire une installation dans un autre dossier
# modifier ce script si installation par https ou exécuter son code à la main

mkdir -p $HOME/docker-magento/ludilabel
cd $HOME/docker-magento/ludilabel
curl -sO https://raw.githubusercontent.com/ludilabel/docker-magento/master/lib/docker-magento-install
source docker-magento-install

# Se positionner ensuite dans le chemin /compose pour lancer les commandes bin/* du projet docker-magento (?)
echo "Vous pouvez maintenant exécuter les commandes bin/*"
cd $HOME/docker-magento/ludilabel/compose

# nettoyage
rm $HOME/docker-magento/ludilabel/docker-magento-install
