#!/usr/bin/env bash

mkdir -p ~/docker-magento/ludilabel
cd ~/docker-magento/ludilabel
curl -sO https://raw.githubusercontent.com/ludilabel/docker-magento/master/lib/install
bash install

# Se positionner ensuite dans le chemin /compose pour lancer les commandes bin/* du projet docker-magento (?)
echo "Vous pouvez maintenant exécuter les commandes bin/*"
cd ~/docker-magento/ludilabel/compose