services:
  app:
    healthcheck:
      test: 'curl --fail -L -k http://172.17.0.1:80'
      interval: 60s
      timeout: 10s
      retries: 5
    depends_on:
      phpfpm:
        condition: service_started

  phpfpm:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      # opensearch:
      #  condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  db:
    healthcheck:
      test: 'mysqladmin ping -h localhost -u root -pmagento'
      interval: 60s
      timeout: 5s
      retries: 2

  redis:
    healthcheck:
      test: 'redis-cli ping || exit 1'
      interval: 60s
      timeout: 5s
      retries: 2

  #opensearch:
  #  healthcheck:
  #    test: 'curl --fail opensearch:9200/_cat/health >/dev/null || exit 1'
  #    interval: 5s
  #    timeout: 5s
  #    retries: 20

  elasticsearch:
    healthcheck:
      test: 'curl --fail elasticsearch:9200/_cat/health >/dev/null || exit 1'
      interval: 60s
      timeout: 5s
      retries: 2

  rabbitmq:
    healthcheck:
      test: 'rabbitmq-diagnostics -q ping'
      interval: 60s
      timeout: 5s
      retries: 2

  mailcatcher:
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider 127.0.0.1:1080 || exit 1'
